apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: isodate-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: isodate-service
    spec:
      containers:
      - name: aggregator-service
        image: eu.gcr.io/deploying-software-on-kubernetes/isodate-service:1.0
        ports:
        - containerPort: 8888
